version: "3.8"

services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      app:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://app:3000
      - CYPRESS_video=true
      - CYPRESS_screenshotOnRunFailure=true
    volumes:
      - ./test/results:/app/results
    networks:
      - travel-app-network
    entrypoint: ["sh", "-c"]
    command: ["sleep 1 && npm run test:checklist-integrated"] 